### ISSUE TITLE
Code modularization

### ISSUE THREAD

**Issue by Aqurds** [Sonikak004/To-Do-list#12]
I see the whole code is very minimized and I appreciate this :+1: You have done a great job :1st_place_medal: 

The code is modularized, but I think you have a better chance to make it more modularized by outsourcing some code from index.js files. I suggest you check and optimize more.

I love how you coded in a very minimized fashion. Great work :+1:

**Comment by melkamu12** [comment]
- You did great job and I appreciate greatly.
