### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by SanaTameem** [Sonikak004/To-Do-list#13]
# Hey @Sonikak004  👋🏻 

You have done a great job so far. 👍🏻  But there are still some issues you have to fix them. ♻️ 

![soClose](https://github.com/Sonikak004/To-Do-list/assets/71990110/dafd739d-29f4-4cee-ab1e-f3bd740bc0e5)

Highlights : 
✅ Good UI
✅ Clean code
✅ Good implementation of requirements

 https://github.com/Sonikak004/To-Do-list/blob/2b90ed5e79976c0a0302a5b2267deb7ea7b68225/src/index.js#L2

https://github.com/Sonikak004/To-Do-list/blob/2b90ed5e79976c0a0302a5b2267deb7ea7b68225/src/index.js#L5

- Try to remove disabling of eslint as it is not a good coding practice.

**Comment by Sonikak004** [comment]
Thank you for reviewing, I will try to fix that and remove eslint disables from my project 😀
